# Generated by Django 5.0.2 on 2024-02-11 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1000)),
                ('took_park', models.PositiveSmallIntegerField()),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TopicCallback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=128)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forumtopic')),
            ],
        ),
    ]
