# Generated by Django 5.0.2 on 2024-02-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('surname', models.CharField(db_index=True, max_length=128)),
                ('email', models.CharField(db_index=True, max_length=128)),
                ('logo', models.ImageField(upload_to='static/media/user_logo')),
                ('is_admin', models.BooleanField()),
                ('is_moderator', models.BooleanField()),
                ('is_activist', models.BooleanField()),
                ('is_scientist', models.BooleanField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
