# Generated by Django 5.0.2 on 2024-02-11 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankProtectionStructures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('short_description', models.CharField(max_length=1000)),
                ('full_description', models.TextField()),
                ('photo', models.ImageField(upload_to='stativ/media/protection_photo/from_scientists')),
                ('mark', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=128)),
                ('build_date', models.DateField(blank=True, null=True)),
                ('last_repair_date', models.DateField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BankProtectionTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('active', models.BooleanField()),
                ('photo', models.ImageField(upload_to='static/media/protection_photos/from_comments')),
                ('text', models.CharField(max_length=256)),
                ('publish_date', models.DateField(auto_now=True)),
                ('obj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.bankprotectionstructures')),
            ],
        ),
    ]
