# Generated by Django 5.0.2 on 2024-02-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankprotectionstructures',
            name='prognosis',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
